<?php

/**
 * @file
 * Install file for the ollama provider module.
 */

/**
 * Implements hook_install().
 */
function ai_provider_ollama_install() {
  $config_factory = \Drupal::configFactory();

  // Check if we have old configuration from the AI submodule.
  $old_config = $config_factory->get('provider_ollama.settings');
  $old_data = $old_config->getRawData();
  if (!empty($old_data['host_name'])) {
    $new_config = $config_factory->getEditable('ai_provider_ollama.settings');

    // Bail if we already have data.
    $new_data = $new_config->getRawData();
    if (!empty($new_data['host_name'])) {
      return;
    }

    // Copy the old configuration from the previous AI submodule into the new
    // external module.
    $new_config->setData($old_data);
    $new_config->save();
  }

  // Uninstall the old submodule of AI core if it is still installed.
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $handler */
  $handler = \Drupal::service('module_handler');
  if ($handler->moduleExists('ai_provider_ollama')) {
    /** @var \Drupal\Core\Extension\ModuleInstallerInterface $installer */
    $installer = \Drupal::service('module_installer');
    $installer->uninstall(['provider_ollama']);
  }
}

/**
 * Implements hook_uninstall().
 */
function ai_provider_ollama_uninstall() {
  $state = \Drupal::service('state');
  $state->delete('ai_provider_ollama.models');
}
